\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{pset}
\LoadClass{article}
\RequirePackage{pset}
\RequirePackage{mathpartir}
\RequirePackage{amsmath}
\RequirePackage{amssymb}
\RequirePackage{hyperref}

% Page layout %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\RequirePackage[letterpaper,margin=1in]{geometry}
\pagestyle{empty}
\setlength\parindent{0in}
\addtolength\parskip{0.1cm}
\setlength\fboxrule{.5mm}\setlength{\fboxsep}{1.2mm}
\newlength\boxlength\setlength\boxlength\textwidth
\addtolength\boxlength{-4mm}


